body:
- type: textarea
  attributes:
    label: Introductions
    description: Hello! Can you introduce yourself in a couple sentences?
- type: input
  attributes:
    label: My Blogroll
    description: Link to your shiny new blogroll
  validations:
    required: true
- type: textarea
  attributes:
    label: Required Reading
    description: What do we need to read? Share up to 5 latest posts from your blogroll
- type: input
  attributes:
    label: My Link
    description: Do you have a personal page or blog we shoud check out?
